[package]
authors = ["panicbit <panicbit.dev@gmail.com>"]
name = "aoc"
version = "0.1.0"

[dependencies]
cachedir = "0.1.1"
clap = "2.28.0"
failure = "0.1.1"
preferences = "1.1.0"
reqwest = "0.8.1"
structopt-derive = "0.1.6"
